# 04classify.sub
#
#
# Specify the HTCondor Universe
universe = vanilla
log = 04classify_$(Cluster).log
error = 04classify_$(Cluster)_$(Process).err
requirements = (OpSysAndVer =?= "SL6")
#
# Specify your executable, arguments, and a file for HTCondor to store standard
#  output.
executable = 04classify.sh
arguments = $(samplename)
output = 04classify_$(Cluster).out
#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
#transfer_input_files =
#transfer_output_files =
#
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.
Requirements = (Target.HasGluster == true)
request_cpus = 3
request_memory = 1GB
request_disk = 7GB
#
# Tell HTCondor to run every fastq file in the provided list:
queue samplename from splitfastqsab
