# 07.2nrdb_gff.sub
#
#
# Specify the HTCondor Universe
universe = vanilla
log = 07.2nrdb_gff_$(Cluster).log
error = 07.2nrdb_gff_$(Cluster)_$(Process).err
requirements = (OpSys == "LINUX") && (OpSysMajorVer == 6)
#
# Specify your executable, arguments, and a file for HTCondor to store standard
#  output.
executable = /home/amlinz/executables/07.2nrdb_gff.sh
#arguments = $(samplename)
output = 07.2nrdb_gff_$(Cluster).out
#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /home/amlinz/zipped/genometools.tar.gz,http://proxy.chtc.wisc.edu/SQUID/amlinz/unprocessed-nrdb.gff.gz
#transfer_output_files = CDS_$(samplename).fna
#
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.
Requirements = (Target.HasGluster == true)
request_cpus = 1
request_memory = 10GB
request_disk = 6GB
#
# Tell HTCondor to run every fastq file in the provided list:
queue
