# 12genekey.sub
#
#
# Specify the HTCondor Universe
universe = vanilla
log = 12genekey_$(Cluster).log
error = 12genekey_$(Cluster)_$(Process).err
requirements = (OpSys == "LINUX") && (Target.HasGluster == true)
#
# Specify your executable, arguments, and a file for HTCondor to store standard
#  output.
executable = executables/12genekey.sh
output = 12genekey_$(Cluster).out
#arguments = $(filepart)
#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = Mendota_ID90_2018-03-02.readcounts.txt.gz,Trout_ID90_2018-03-02.readcounts.txt.gz,Sparkling_ID90_2018-03-02.readcounts.txt.gz,scripts/genekey.py,zipped/python.tar.gz
#transfer_output_files =
#
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.

request_cpus = 1
request_memory = 8GB
request_disk = 4GB
#
queue
