# 13sample_metaG.sub
#
#
# Specify the HTCondor Universe
universe = vanilla
log = 13sample_metaG_$(Cluster).log
error = 13sample_metaG_$(Cluster)_$(Process).err
#
# Specify your executable, arguments, and a file for HTCondor to store standard
#  output.
executable = executables/13sample_metaG.sh
arguments = $(sample)
output = 13sample_metaG_$(Cluster).out
#
# No files to transfer, since it's going to interact with Gluster instead of the submit node
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = zipped/BBMap_36.99.tar.gz
transfer_output_files =
#
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.
Requirements = (Target.HasGluster == true)
request_cpus = 1
request_memory = 16 GB
request_disk = 108 GB
#
# Submit jobs
queue sample from metaG_samples.txt
