#15binning.sub
#
universe = vanilla
# Name the log file:
log = 15binning.log

# Name the files where standard output and error should be saved:
output = 15binning.out
error = 15binning.err

executable = executables/15binning.sh

# If you wish to compile code, you'll need the below lines. 
#  Otherwise, LEAVE THEM OUT if you just want to interactively test!
requirements = ( OpSysMajorVer == 7 ) && ( Target.HasGluster == true )
arguments = $(metaG)

# Indicate all files that need to go into the interactive job session,
#  including any tar files that you prepared:
transfer_input_files = MaxBin.tar.gz

# It's still important to request enough computing resources. The below 
#  values are a good starting point, but consider your file sizes for an
#  estimate of "disk" and use any other information you might have
#  for "memory" and/or "cpus".

request_cpus = 1
request_memory = 24GB
request_disk = 16GB

queue metaG from metaG_samples.txt
