# 05metagenome_assemblies.sub
#
#
# Specify the HTCondor Universe
universe = vanilla
log = 05metagenome_assemblies_$(Cluster).log
error = 05metagenome_assemblies_$(Cluster)_$(Process).err
requirements = (OpSys == "LINUX") && (OpSysMajorVer == 6) && (Arch == "X86_64")
#
# Specify your executable, arguments, and a file for HTCondor to store standard
#  output.
executable = /home/amlinz/executables/05metagenome_assemblies.sh
arguments = $(samplename)
output = 05metagenome_assemblies_$(Cluster).out
#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /home/amlinz/zipped/genometools.tar.gz,/home/amlinz/metaG_gffs/$(samplename)
transfer_output_files = CDS_$(samplename).fna
#
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.
Requirements = (Target.HasGluster == true)
request_cpus = 1
request_memory = 16GB
request_disk = 4GB
#
# Tell HTCondor to run every fastq file in the provided list:
queue samplename from /home/amlinz/metaG_gffs.txt

