# 13map_metaGs.sub
#
#
# Specify the HTCondor Universe
universe = vanilla
log = 13map_metaGs_$(Cluster).log
error = 13map_metaGs_$(Cluster)_$(Process).err
requirements = (OpSys == "LINUX")
#
# Specify your executable, arguments, and a file for HTCondor to store standard
#  output.
executable = executables/13map_metaGs.sh
arguments = $(metaG)
output = 13map_metaGs_$(Cluster).out
#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = zipped/BBMap_36.99.tar.gz,zipped/samtools.tar.gz
#transfer_output_files = 
#
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.
Requirements = (Target.HasGluster == true)
request_cpus = 1
request_memory =72GB
request_disk = 48GB
#
# Tell HTCondor to run every fastq file in the provided list:
queue metaG from path2metaGfastqs.txt

